services:
  enthro-backend:
    depends_on:
      - redis
    image: enthro.azurecr.io/enthro-backend:latest
    container_name: enthro-backend
    restart: always
    ports:
      - "80:80"
    env_file: .env
    networks:
      - enthro-net
  
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
    networks:
      - enthro-net

volumes:
  redis-data:

networks:
  enthro-net:
    driver: bridge