name: Trigger auto deployment for enthro

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/enthro-AutoDeployTrigger-435d7c98-4c9a-4eec-bf68-4b61db2531e8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ENTHRO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ENTHRO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ENTHRO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: enthro.azurecr.io
          registryUsername: ${{ secrets.ENTHRO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ENTHRO_REGISTRY_PASSWORD }}
          containerAppName: enthro
          resourceGroup: dev
          imageToBuild: enthro.azurecr.io/enthro:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


